<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add student scholar');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/student_scholar.php';
    $dbh_student_scholar = new student_scholar;

    $object_name = 'dbh_student_scholar';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_student_scholar.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_student_scholar->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_student_scholar->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($dbh_student_scholar->check_uniqueness_for_student_scholar($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists!";
        }

        if($message=="")
        {
            $dbh_student_scholar->add($arr_form_data);
            

            redirect("listview_student_scholar.php?$query_string");
        }
    }
}
require 'subclasses/student_scholar_html.php';
$html = new student_scholar_html;
$html->draw_header('Add %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);


// $html->fields['student_id']['list_settings']['query'] = "SELECT student.student_id AS `Queried_student_id`, student_no FROM student LEFT JOIN student_scholar ON student_scholar.student_id = student.student_id  WHERE student_scholar.is_active != 'Yes' AND student.is_active = 'Yes' ORDER BY `Queried_student_id`";
$html->draw_controls('add');

$html->draw_footer();