<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit student scholar');

if(isset($_GET['student_scholar_id']))
{
    $student_scholar_id = urldecode($_GET['student_scholar_id']);
    require 'form_data_student_scholar.php';

}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/student_scholar.php';
    $dbh_student_scholar = new student_scholar;

    $object_name = 'dbh_student_scholar';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_student_scholar.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_student_scholar->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_student_scholar->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {

            $dbh_student_scholar->edit($arr_form_data);

            redirect("listview_student_scholar.php?$query_string");
        }
    }
}
require 'subclasses/student_scholar_html.php';
$html = new student_scholar_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('student_scholar_id');

$html->draw_controls('edit');

$html->draw_footer();