<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add job post');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/job_post.php';
    $dbh_job_post = new job_post;

    $object_name = 'dbh_job_post';
    require 'components/create_form_data.php';
    extract($arr_form_data);
    $reservation_time_in = $_POST['reservation_time_in'];
    $reservation_time_out = $_POST['reservation_time_out'];
    $minutes = $_POST['minutes'];
    $am_pm = $_POST['am_pm'];
    $minutes1 = $_POST['minutes1'];
    $am_pm1 = $_POST['am_pm1'];


    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_job_post.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
      // debug($_POST['minutes']);
      // debug($_POST['reservation_time_in']);
      // debug($_POST['am_pm']);
      $time_in = $_POST['reservation_time_in'] . ':' . $_POST['minutes'] . ' ' . $_POST['am_pm'];
$time_out = $_POST['reservation_time_out'] . ':' . $_POST['minutes1'] . ' ' . $_POST['am_pm1'];
$a = date('h:i A', strtotime($time_in));
// debug($a);


if($time_in >= '07:30 PM' && $time_in <= '07:50 AM')
{
  echo "K";
}
        log_action('Pressed submit button');

        $message .= $dbh_job_post->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($am_pm == '')
        {
          $message .= "No value detected: Reservation Time In Meridiem <br>";
        }
        if($am_pm1 == '')
        {
          $message .= "No value detected: Reservation Time Out Meridiem <br>";
        }
        if($minutes == '')
        {
          $message .= "No value detected: Reservation Time In Minutes <br>";
        }
        if($minutes1 == '')
        {
          $message .= "No value detected: Reservation Time Out Minutes ";
        }
        debug($time_in);
        debug($time_out);

        if($dbh_job_post->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
          require 'components/get_auto_id.php';

          $d = get_max('job_post');
          $year = date('Y');

          $str = str_pad($d, 5, 0, STR_PAD_LEFT);
          // debug($str);

          $job_post_no = 'JP' . $year . '-' . $str;
          // debug($job_post_no);
          $arr_form_data['job_post_no'] = $job_post_no;
          $arr_form_data['job_created'] = date('Y-m-d h:i:s');
            if(isset($_SESSION['dept_id']))
            {
                $arr_form_data['dept_id'] = $_SESSION['dept_id'];
            }
            $arr_form_data['reservation_time_in'] = $_POST['reservation_time_in'] . ':' . $_POST['minutes'] . ' ' . $_POST['am_pm'];
            $arr_form_data['reservation_time_out'] = $_POST['reservation_time_out'] . ':' . $_POST['minutes1'] . ' ' . $_POST['am_pm1'];

            // $dbh_job_post->add($arr_form_data);

//
            // redirect("listview_job_post.php?$query_string");
        }
    }
}
require 'subclasses/job_post_html.php';
$html = new job_post_html;
$html->draw_header('Add %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
init_var($_POST["minutes"]);
init_var($_POST['am_pm']);
$select = '<select name="minutes">
                <option value="" ';
                if($_POST["minutes"] == "")
                {
                  $select .= "selected";
                }
                $select .= '></option>
                <option value="00" ';
                if($_POST["minutes"] == "00")
                {
                  $select .= "selected";
                }
                $select .= '>00</option>
                <option value="10" ';
                if($_POST["minutes"] == 10)
                {
                   $select .= "selected";
                }
                $select .= '>10</option>
                <option value="20" ';
                if($_POST["minutes"] == 20)
                {
                   $select .= "selected";
                }
                $select .= '>20</option>
                <option value="30" ';
                if($_POST["minutes"] == 30)
                {
                   $select .= "selected";
                }
                $select .= '>30</option>
                <option value="40" ';
                if($_POST["minutes"] == 40)
                {
                   $select .= "selected";
                }
                $select .= '>40</option>
                <option value="50" ';
                if($_POST["minutes"] == 50)
                {
                   $select .= "selected";
                }
                $select .= '>50</option>
              </select>

              <select name="am_pm">
                  <option value="" ';
                  if($_POST["am_pm"] == "")
                  {
                    $select .= "selected";
                  }
                  $select .= '></option>
                  <option value="AM" ';
                  if($_POST["am_pm"] == "AM")
                  {
                    $select .= "selected";
                  }
                  $select .= '>AM</option>
                  <option value="PM" ';
                  if($_POST["am_pm"] == "PM")
                  {
                     $select .= "selected";
                  }
                  $select .= '>PM</option>
              </select>';

init_var($_POST["minutes1"]);
init_var($_POST['am_pm1']);
$select1 = '<select name="minutes1">
                <option value="" ';
                if($_POST["minutes1"] == "")
                {
                  $select1 .= "selected";
                }
                $select1 .= '></option>
                <option value="00" ';
                if($_POST["minutes1"] == "00")
                {
                  $select1 .= "selected";
                }
                $select1 .= '>00</option>
                <option value="10" ';
                if($_POST["minutes1"] == 10)
                {
                   $select1 .= "selected";
                }
                $select1 .= '>10</option>
                <option value="20" ';
                if($_POST["minutes1"] == 20)
                {
                   $select1 .= "selected";
                }
                $select1 .= '>20</option>
                <option value="30" ';
                if($_POST["minutes1"] == 30)
                {
                   $select1 .= "selected";
                }
                $select1 .= '>30</option>
                <option value="40" ';
                if($_POST["minutes1"] == 40)
                {
                   $select1 .= "selected";
                }
                $select1 .= '>40</option>
                <option value="50" ';
                if($_POST["minutes1"] == 50)
                {
                   $select1 .= "selected";
                }
                $select1 .= '>50</option>
              </select>
              <select name="am_pm1">
                  <option value="" ';
                  if($_POST["am_pm1"] == "")
                  {
                    $select1 .= "selected";
                  }
                  $select1 .= '></option>
                  <option value="AM" ';
                  if($_POST["am_pm1"] == "AM")
                  {
                    $select1 .= "selected";
                  }
                  $select1 .= '>AM</option>
                  <option value="PM" ';
                  if($_POST["am_pm1"] == "PM")
                  {
                     $select1 .= "selected";
                  }
                  $select1 .= '>PM</option>
              </select>';

$html->fields['reservation_time_in']['companion'] = $select;
$html->fields['reservation_time_out']['companion'] = $select1;

$html->draw_controls('add');

$html->draw_footer();
