<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('View job post');

$page_title       = 'ListView: %%';
$db_subclass      = 'job_post';
$html_subclass    = 'job_post_html';
$arr_pkey_name    = array('job_post_id');
$results_per_page = LISTVIEW_RESULTS_PER_PAGE;

//user links / passport tags
$add_link         = 'Add job post';
$edit_link        = 'Edit job post';
$delete_link      = 'Delete job post';
$view_link        = 'View job post';
$reserve          = '';
//pages - set to empty if you don't want to include them in the listview
$add_page         = 'add_job_post.php';
$edit_page        = 'edit_job_post.php';
$delete_page      = 'delete_job_post.php';
$view_page        = 'detailview_job_post.php';
$reserve          = '';
$csv_page         = 'csv_job_post.php';
$report_page      = 'reporter_job_post.php';

//Extra entries under operations column (name of include file, not html code)
if(isset($_SESSION['student_no']))
{
	$operations = 'operation_reserve.php';
}
elseif(isset($_SESSION['dept_id']))
{
	$operations = 'operation_reserved_students.php';
}
else
{
	$operations = 'operation_reserved_students.php';
}
$operations_extra = $operations;



//Formatting and alignment options for data columns
$arr_formatting   = array();
$arr_alignment    = array();



// debug();



//For custom join & select clause, you need to set the following variables so that the default
//listview components do not rely on DD data
$join_clause       = '';
if(isset($_SESSION['dept_id']))
{
		$where_clause      = " dept.dept_id =  '".$_SESSION['dept_id']."' ";
}
else
{
		$where_clause      = "";
}
$lst_fields        = '';
$arr_fields        = '';
$arr_field_labels  = '';
$lst_filter_fields = '';
$arr_filter_field_labels = '';
$arr_subtext_separators  = '';

//ORDER BY clause to use before a user clicks an ascending/descending column arrow.
$default_sort_order = '';

//Uncomment $print_settings and enable DEBUG_MODE to show the values of the settings for custom join & select
// $print_settings=TRUE;


require 'components/listview_proc_head.php';
require 'components/listview_proc_html.php';
require 'components/listview_proc_query.php';
require 'components/listview_body_head.php';
require 'components/listview_body_data.php';
require 'components/listview_body_end.php';
init_var($_POST['btn_submit']);
init_var($_POST['job_post']);

	// debug($job_post_no);


if($_POST['btn_submit'])
{
// debug($_SESSION['student_no']);
	$dbh = cobalt_load_class('student_scholar');
	$dbh->set_fields('student_scholar_id');
	$dbh->set_table('student_scholar left join student on student.student_id = student_scholar.student_id');
	$dbh->set_where('student_no = "'.$_SESSION['student_no'].'" ');
	$dbh->exec_fetch('single');
	$student_id = $dbh->dump['student_scholar_id'];
// debug($dbh->query);
	require_once 'subclasses/reservation.php';
	$dbh_reservation = new reservation;

  $object_name = 'dbh_reservation';
  require 'components/create_form_data.php';
  extract($arr_form_data);

	$arr_form_data['job_post_id'] = $_POST['job_post'];
	$arr_form_data['student_scholar_id'] = $student_id;

// debug($_POST['job_post']);
		// debug($arr_form_data);
    $dbh_reservation->add($arr_form_data);

// debug($arr_form_data);

}

if(isset($_GET['job_post_id']))
{
	if($_GET['job_post_id'])
	{
		$job_post = $_GET['job_post_id'];
	}

	if($_POST['job_post'])
	{
		$job_post = $_POST['job_post'];
	}
?>

<div id="overlay" style="position:fixed;top:1px;right:1px;width:100%;height:100%;background-color:RGBA(255,255,255,.3)">
<?php
$modal = cobalt_load_class("user_html");
$modal->draw_header();
?>
<input type="hidden" name ="job_post" value="<?php echo $job_post;?>">
<?php

$modal->draw_container_div_start();

if($_GET['job_post'] == 'foremp')
{
$modal->draw_fieldset_header('List of Reserved Students');
$modal->draw_fieldset_body_start();
echo '<table>';

	$dbh = cobalt_load_class('reservation');
	$dbh->set_table(' reservation left join student_scholar on student_scholar.student_scholar_id = reservation.student_scholar_id
		left join student on student.student_id = student_scholar.student_id
		left join person on person.person_id = student.person_id');
	$dbh->set_fields('student_no, first_name, middle_name, last_name');
	$dbh->set_where('job_post_id = "'.$_GET['job_post_id'].'" ');
	$dbh->exec_fetch('array');
	$student_id = $dbh->dump;
	// debug(count($student_id['student_no']));
	if($dbh->num_rows > 0)
	{
		for ($i=0; $i < count($student_id['student_no']) ; $i++)
		{
			echo '<tr><td>Student No: </td><td>&nbsp;'.$student_id['student_no'][$i].'</td></tr>';
			echo '<tr><td>Student Student Name: </td><td>&nbsp;'.$student_id['last_name'][$i].', '.$student_id['first_name'][$i].' '.$student_id['middle_name'][$i].'</td></tr>';
			echo '<tr><td></td><td>&nbsp;</td></tr>';
		}
	}
	else {
		echo 'No Student Reservation';
	}

echo '</table>';
$modal->draw_fieldset_body_end();
$modal->draw_fieldset_footer_start();
$modal->draw_button('cancel');
$modal->draw_fieldset_footer_end();
}
else
{
$modal->draw_fieldset_header('Confirmation');
$modal->draw_fieldset_body_start();
echo 'Are you sure you want to Reserve?';
$modal->draw_fieldset_body_end();
$modal->draw_fieldset_footer_start();
$modal->draw_Submit_Cancel();
$modal->draw_fieldset_footer_end();
}

$modal->draw_container_div_end();

?>

</div>
<?php
}
?>
