<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add request job');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/request_job.php';
    $dbh_request_job = new request_job;

    $object_name = 'dbh_request_job';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_request_job.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_request_job->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_request_job->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
          require 'components/get_auto_id.php';

          $d = get_max('request_job');
          $year = date('Y');

          $str = str_pad($d, 5, 0, STR_PAD_LEFT);
          // debug($str);

          $request_job_no = 'RJ' . $year . '-' . $str;
          // debug($job_post_no);
          $arr_form_data['request_job_no'] = $request_job_no;
          $arr_form_data['request_created'] = date('Y-m-d h:i:s');
            $dbh_request_job->add($arr_form_data);


            redirect("listview_request_job.php?$query_string");
        }
    }
}
require 'subclasses/request_job_html.php';
$html = new request_job_html;
$html->draw_header('Add %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);


$html->fields['student_scholar_id']['list_settings']['query'] = "SELECT     student.student_id AS `Queried_student_id`,
                                                                            student.student_no

                                                                 FROM       student

                                                                 LEFT JOIN  student_scholar
                                                                 ON         student_scholar.student_id = student.student_id


                                                                 WHERE      student.student_id = student_scholar.student_id

                                                                 ORDER BY `student_no`";
// init_var($_POST['dept_id']);
// if($_POST['dept_id'])
// {
//   $html->fields['dept_id']['list_settings']['query'] = "SELECT first_name, last_name, middle_name, employee.emp_id As 'Queried_employee_id' from employee
//                                                                     left join person on person.person_id = employee.person_id
//                                                                     where dept_id = '".$_POST['dept_id']."'";
// }
// debug($html->fields['dept_id']['list_settings']['query']);
$html->draw_controls('add');

$html->draw_footer();
