<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('View request job');

$page_title       = 'ListView: %%';
$db_subclass      = 'request_job';
$html_subclass    = 'request_job_html';
$arr_pkey_name    = array('request_job_id');
$results_per_page = LISTVIEW_RESULTS_PER_PAGE;

//user links / passport tags
$add_link         = 'Add request job';
$edit_link        = 'Edit request job';
$delete_link      = 'Delete request job';
$view_link        = 'View request job';

//pages - set to empty if you don't want to include them in the listview
$add_page         = 'add_request_job.php';
$edit_page        = 'edit_request_job.php';
$delete_page      = 'delete_request_job.php';
$view_page        = 'detailview_request_job.php';
$csv_page         = 'csv_request_job.php';
$report_page      = 'reporter_request_job.php';

//Extra entries under operations column (name of include file, not html code)
if(isset($_SESSION['dept_id']))
{
	$operations_extra = 'operation_approvedeny_request.php';
}
// $operations_extra = '';

//Formatting and alignment options for data columns
$arr_formatting   = array();
$arr_alignment    = array();

//For custom join & select clause, you need to set the following variables so that the default
//listview components do not rely on DD data



$join_clause       = '';
if(isset($_SESSION['student_no']))
{
	$where = 'student_no = "'.$_SESSION['student_no'].'" ';
}
elseif(isset($_SESSION['dept_id']))
{
 	$where = "request_job.dept_id = '".$_SESSION['dept_id']."'";
}
else
{
	$where = '';
}

$where_clause = $where;
$lst_fields        = '';
$arr_fields        = '';
$arr_field_labels  = '';
$lst_filter_fields = '';
$arr_filter_field_labels = '';
$arr_subtext_separators  = '';


// debug($_SESSION['student_no']);
//ORDER BY clause to use before a user clicks an ascending/descending column arrow.
$default_sort_order = '';

//Uncomment $print_settings and enable DEBUG_MODE to show the values of the settings for custom join & select
// $print_settings=TRUE;

require 'components/listview_proc_head.php';
require 'components/listview_proc_html.php';
require 'components/listview_proc_query.php';
require 'components/listview_body_head.php';
require 'components/listview_body_data.php';
require 'components/listview_body_end.php';


init_var($_GET['status']);
init_var($_GET['request_job_id']);
// debug($_GET['request_job_id']);
if($_GET['status'] == 'Approve')
{
	$d = cobalt_load_class('request_job');
	$param = array(
		'status' => 'Approved',
		'request_job_id' => $_GET['request_job_id']
	);
	// debug($param);
	$d->update_status($param);
}
else
{
	$d = cobalt_load_class('request_job');
	$param = array(
		'status' => 'Denied',
		'request_job_id' => $_GET['request_job_id']
	);
	// debug($param);
	$d->update_status($param);
}
