<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('View reservation');

$page_title       = 'ListView: %%';
$db_subclass      = 'reservation';
$html_subclass    = 'reservation_html';
$arr_pkey_name    = array('reservation_job_post_id');
$results_per_page = LISTVIEW_RESULTS_PER_PAGE;

//user links / passport tags
$add_link         = 'Add reservation';
$edit_link        = 'Edit reservation';
$delete_link      = 'Delete reservation';
$view_link        = 'View reservation';

//pages - set to empty if you don't want to include them in the listview
$add_page         = 'add_reservation.php';
$edit_page        = 'edit_reservation.php';
$delete_page      = 'delete_reservation.php';
$view_page        = 'detailview_reservation.php';
$csv_page         = 'csv_reservation.php';
$report_page      = 'reporter_reservation.php';

//Extra entries under operations column (name of include file, not html code)
$operations_extra = '';

//Formatting and alignment options for data columns
$arr_formatting   = array();
$arr_alignment    = array();

if(isset($_SESSION['student_no']))
{
  $where = "student.student_no = '".$_SESSION['student_no']."'";
}
elseif(isset($_SESSION['dept_id']))
{
  $where = "dept_id = '".$_SESSION['dept_id']."'";
}
else{
  $where = '';
}
// debug($_SESSION['dept_id']);

//For custom join & select clause, you need to set the following variables so that the default
//listview components do not rely on DD data
$join_clause = '`reservation` LEFT JOIN `job_post` ON `reservation`.`job_post_id` = `job_post`.`job_post_id`
			LEFT JOIN `student_scholar` ON `reservation`.`student_scholar_id` = `student_scholar`.`student_scholar_id`
			left join student on student.student_id = student_scholar.student_id';
$where_clause = $where;
$lst_fields = 'reservation.reservation_job_post_id, `reservation`.`job_post_id`,`mydb`.`job_post`.`job_post_no` AS `mydb_job_post_job_no`,
`mydb`.`student`.`student_no` AS `mydb_student_scholar_student_no`';
$arr_fields = array(array('mydb_job_post_job_no',
                         ),
                    array('mydb_student_scholar_student_no',
                         ),
                   );
$arr_field_labels = array('Job Post',
                          'Student Scholar',
                         );
$lst_filter_fields = '`mydb`.`job_post`.`job_post_no`,`mydb`.`student`.`student_no`';
$arr_filter_field_labels = array('Job Post',
                                 'Student Scholar',
                                );
$arr_subtext_separators = array(array(                                     ),
                                array(                                     ),
                               );

//ORDER BY clause to use before a user clicks an ascending/descending column arrow.
$default_sort_order = '';

//Uncomment $print_settings and enable DEBUG_MODE to show the values of the settings for custom join & select
// $print_settings=TRUE;


require 'components/listview_proc_head.php';
require 'components/listview_proc_html.php';
require 'components/listview_proc_query.php';
require 'components/listview_body_head.php';
require 'components/listview_body_data.php';
require 'components/listview_body_end.php';
