<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('View record');

$page_title       = 'ListView: %%';
$db_subclass      = 'record';
$html_subclass    = 'record_html';
$arr_pkey_name    = array('record_id');
$results_per_page = LISTVIEW_RESULTS_PER_PAGE;

//user links / passport tags
$add_link         = 'Add record';
$edit_link        = 'Edit record';
$delete_link      = 'Delete record';
$view_link        = 'View record';

//pages - set to empty if you don't want to include them in the listview
$add_page         = 'add_record.php';
$edit_page        = 'edit_record.php';
$delete_page      = 'delete_record.php';
$view_page        = 'detailview_record.php';
$csv_page         = 'csv_record.php';
$report_page      = 'reporter_record.php';

//Extra entries under operations column (name of include file, not html code)
// if(isset($_SESSION['dept_id']))
// {
// 	$operations_extra = 'operation_approvedeny_record.php';
// }
$operations_extra = '';

//Formatting and alignment options for data columns
$arr_formatting   = array();
$arr_alignment    = array();

//For custom join & select clause, you need to set the following variables so that the default
//listview components do not rely on DD data
// $join_clause       = '';
// $where_clause      = "";
// $lst_fields        = '';
// $arr_fields        = '';
// $arr_field_labels  = '';
// $lst_filter_fields = '';
// $arr_filter_field_labels = '';
// $arr_subtext_separators  = '';

// debug($_SESSION['student_no']);


$join_clause = '`record` LEFT JOIN `dept` ON `record`.`dept_id` = `dept`.`dept_id`
LEFT JOIN `job_post` ON `record`.`job_post_id` = `job_post`.`job_post_id`
LEFT JOIN `student_scholar` ON `record`.`student_scholar_id` = `student_scholar`.`student_scholar_id`
LEFT JOIN `request_job` ON `record`.`request_job_id` = `request_job`.`request_job_id`
LEFT JOIN student on student.student_id = student_scholar.student_id';

if(isset($_SESSION['dept_id']))
{
 	$where = "record.dept_id = '".$_SESSION['dept_id']."'";
}
elseif(isset($_SESSION['student_no']))
{
	$where = "student_no = '".$_SESSION['student_no']."'";
}
else{
  $where = '';
}
$where_clause = $where;
$lst_fields = '`record`.`record_id`,`mydb`.`dept`.`dept_code` AS `mydb_dept_dept_code`,`mydb`.`job_post`.`job_post_id` AS `mydb_job_post_job_post_id`,`mydb`.`job_post`.`job_post_no` AS `mydb_job_post_job_post_no`,`mydb`.`request_job`.`request_job_id` AS `mydb_request_job_request_job_id`,
	`mydb`.`request_job`.`request_job_no` AS `mydb_request_job_request_job_no`,
	`mydb`.`student_scholar`.`student_scholar_id` AS `mydb_student_scholar_student_scholar_id`,
	`record`.`record_date`,`record`.`record_time_in`,`record`.`record_time_out`';
$arr_fields = array(array('mydb_dept_dept_code',
                         ),
                    array('mydb_job_post_job_post_no',
                         ),
                    array('mydb_request_job_request_job_no',
                         ),
                    array('mydb_student_scholar_student_scholar_id',
                         ),
                    'record_date',
                    'record_time_in',
                    'record_time_out',
                   );
$arr_field_labels = array('Dept',
                          'Job Post',
                          'Request Job',
                          'Student Scholar',
                          'Record Date',
                          'Record Time In',
                          'Record Time Out',
                         );
$lst_filter_fields = '`mydb`.`dept`.`dept_code`,`mydb`.`job_post`.`job_post_id`,`mydb`.`request_job`.`request_job_id`,`mydb`.`student_scholar`.`student_scholar_id`,`record`.`record_date`,`record`.`record_time_in`,`record`.`record_time_out`';
$arr_filter_field_labels = array('Dept',
                                 'Job Post',
                                 'Request Job',
                                 'Student Scholar',
                                 'Record Date',
                                 'Record Time In',
                                 'Record Time Out',
                                );
$arr_subtext_separators = array(array(                                    ),
                                array(                                      ),
                                array(                                     ),
                                array(                                     ),
                               );

//ORDER BY clause to use before a user clicks an ascending/descending column arrow.
$default_sort_order = '';

//Uncomment $print_settings and enable DEBUG_MODE to show the values of the settings for custom join & select
// $print_settings=TRUE;


require 'components/listview_proc_head.php';
require 'components/listview_proc_html.php';
require 'components/listview_proc_query.php';
require 'components/listview_body_head.php';
require 'components/listview_body_data.php';
require 'components/listview_body_end.php';

init_var($_GET['status']);
init_var($_GET['record_id']);
// debug($_GET['request_job_id']);
if($_GET['status'] == 'Approve')
{
	$d = cobalt_load_class('record');
	$param = array(
		'status' => 'Approved',
		'record_id' => $_GET['record_id']
	);
	// debug($param);
	$d->update_status($param);
}
else
{
	$d = cobalt_load_class('record');
	$param = array(
		'status' => 'Denied',
		'record_id' => $_GET['record_id']
	);
	// debug($param);
	$d->update_status($param);
}
